package musescript.builtins;

import musescript.indicators.IndicatorRegistry;

typedef TaSourceEntry = {
	/** MuseScript builtin name ("cmo", "stochastic", …). */
	var name:String;
	/** Human signature line: `cmo(Series, Window) -> Scalar`. */
	var sig:String;
	/** Generated MuseScript demo-strategy source for this indicator. */
	var source:String;
	/** One-line description (from the port's class doc comment; may be ""). */
	var doc:String;
	/** Originating lib/ file name ("Cmo.hx"). */
	var file:String;
	/** Raw MuseType enum-constructor names ("TSeries", "TWindow", …), same spelling `sig`
	 * prettifies for humans — kept structured here so callers (e.g. the native-source parity
	 * test) can build calls without re-parsing `sig`. */
	var argKinds:Array<String>;
	/**
	 * A hand-authored, semantically-equivalent MuseScript reimplementation of this
	 * indicator's logic (an `@indicator("name") function(args) { ... }` block a user
	 * can copy, fork, and tune), when one exists. Null for the (current majority
	 * case) of ports that only have the Haxe implementation -- incremental,
	 * per-indicator opt-in via an optional `static function nativeSource():String`
	 * on the port class (see TaSourcesMacro), not a blanket requirement. Distinct
	 * from `source`, which is always present and is a DEMO STRATEGY that calls the
	 * builtin -- this is the indicator's own computation, not a caller of it.
	 */
	var nativeSource:Null<String>;
}

/**
 * Runtime table of the per-indicator MuseScript sources generated by
 * `TaSourcesMacro` at build time (ROADMAP.md epic 9's toolbelt surface).
 * Reflection-accessible on the Haxe side (`@:keep` + `TaSources.get(name)` /
 * `Reflect`-walkable entries), and exposed inside the language itself
 * through the `ta` global (see TaToolbelt).
 *
 * Any registered indicator the macro could not statically extract is
 * rendered here on first access from its live `IndicatorSpec`, with the
 * SAME `TaSourceRender` the macro used — so the baked and fallback paths
 * produce identical text and every registered indicator is always covered.
 */
@:keep
class TaSources {
	static var table:Map<String, TaSourceEntry>;
	static var sortedNames:Array<String>;

	public static function get(name:String):Null<TaSourceEntry> {
		ensure();
		return table.get(name);
	}

	public static function has(name:String):Bool {
		ensure();
		return table.exists(name);
	}

	/** All indicator names, sorted — stable for palettes/docs/tests. */
	public static function names():Array<String> {
		ensure();
		return sortedNames.copy();
	}

	public static function all():Map<String, TaSourceEntry> {
		ensure();
		return table;
	}

	static function ensure():Void {
		if (table != null) return;
		table = new Map();
		for (e in (TaSourcesMacro.collect() : Array<TaSourceEntry>))
			table.set(e.name, e);
		// Registered indicators the macro skipped → render now, same renderer.
		for (name => spec in IndicatorRegistry.all()) {
			if (table.exists(name)) continue;
			var argKinds = [for (a in spec.args) Type.enumConstructor(a)];
			var retFields:Null<Array<String>> = switch (spec.ret) {
				case TObject(fields): [for (f in fields) f.name];
				default: null;
			};
			table.set(name, {
				name: name,
				sig: TaSourceRender.sig(name, argKinds, retFields),
				source: TaSourceRender.source(name, argKinds, retFields, "", "?"),
				doc: "",
				file: "?",
				argKinds: argKinds,
				nativeSource: null
			});
		}
		sortedNames = [for (n in table.keys()) n];
		sortedNames.sort(Reflect.compare);
	}
}
